# Generated by Django 3.2.4 on 2021-07-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendsystem', '0002_auto_20210716_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='active',
            new_name='is_active',
        ),
    ]
