# Generated by Django 3.1.4 on 2021-07-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsystem', '0003_rename_active_friendrequest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='is_private',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
