# Generated by Django 3.2.4 on 2021-07-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroom', '0002_auto_20210716_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
