# Generated by Django 3.1.4 on 2021-07-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroom', '0004_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
